language: python
jobs:
  include:
    - name: "Python 3.7.4 on Xenial Linux"
      python: 3.7.4
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install pip -U
  - pip3 install -r requirements.txt -U
  - pip3 install pyinstaller -U

script:
  - pyinstaller --console --hidden-import=pkg_resources.py2_warn --onefile main.py -n "main_$TRAVIS_OS_NAME"
  - sleep 1  # Allow pyinstaller to finish writing to stdout
  - ls -l dist
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then chmod u+x "dist/main_$TRAVIS_OS_NAME" ; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "dist/*"
  on:
    tags: true